"""
testrail_client.py
===================
Pushes generated test cases into TestRail (live mode) or writes them to a
local CSV that matches TestRail's import format (mock mode).
"""

import csv
import sys
from pathlib import Path
from typing import List, Dict

sys.path.append(str(Path(__file__).resolve().parent.parent))
from shared.config import config

OUTPUT_DIR = Path(__file__).resolve().parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True)


def export_test_cases(test_cases: List[Dict], suite_name: str = "Generated Suite") -> str:
    """
    Exports test cases either to TestRail via API (live) or to a local CSV
    file matching TestRail's bulk-import column layout (mock).
    Returns a human-readable location/result string.
    """
    use_live = config.require_or_warn(config.testrail_api_key, "TESTRAIL_API_KEY") and \
        config.require_or_warn(config.testrail_base_url, "TESTRAIL_BASE_URL")

    if use_live:
        import requests
        from requests.auth import HTTPBasicAuth

        base = config.testrail_base_url.rstrip("/")
        auth = HTTPBasicAuth(config.testrail_email, config.testrail_api_key)

        # 1. Create a new test suite
        suite_resp = requests.post(
            f"{base}/index.php?/api/v2/add_suite/{config.testrail_project_id}",
            auth=auth, json={"name": suite_name, "description": "Auto-generated by Test Case Generator Agent"},
            timeout=15,
        )
        suite_resp.raise_for_status()
        suite_id = suite_resp.json()["id"]

        # 2. Create a section
        section_resp = requests.post(
            f"{base}/index.php?/api/v2/add_section/{config.testrail_project_id}",
            auth=auth, json={"suite_id": suite_id, "name": "Auto-generated cases"},
            timeout=15,
        )
        section_resp.raise_for_status()
        section_id = section_resp.json()["id"]

        # 3. Add each case
        created = 0
        for tc in test_cases:
            payload = {
                "title": tc["title"],
                "type_id": 7,  # "Other" — adjust to your TestRail case-type IDs
                "priority_id": _priority_to_id(tc.get("priority", "Medium")),
                "custom_steps_separated": [
                    {"content": step, "expected": ""} for step in tc.get("steps", [])
                ],
                "custom_expected": tc.get("expected_result", ""),
                "refs": tc.get("category", ""),
            }
            r = requests.post(
                f"{base}/index.php?/api/v2/add_case/{section_id}",
                auth=auth, json=payload, timeout=15,
            )
            r.raise_for_status()
            created += 1

        return f"Created TestRail suite '{suite_name}' (suite_id={suite_id}) with {created} cases."

    # ---- mock / fallback: write CSV locally ----
    out_path = OUTPUT_DIR / "test_cases_testrail_import.csv"
    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Title", "Category", "Priority", "Preconditions", "Steps", "Expected Result"])
        for tc in test_cases:
            writer.writerow([
                tc["title"],
                tc.get("category", ""),
                tc.get("priority", "Medium"),
                tc.get("preconditions", ""),
                " | ".join(tc.get("steps", [])),
                tc.get("expected_result", ""),
            ])
    print(f"[testrail_client] MOCK MODE: wrote {len(test_cases)} cases to {out_path}")
    return str(out_path)


def _priority_to_id(priority: str) -> int:
    return {"Low": 1, "Medium": 2, "High": 3, "Critical": 4}.get(priority, 2)
