"""
jira_bug_creator.py
====================
Creates a Jira bug ticket for each analyzed failure, including reproduction
steps, severity, and a link to the CI build. Live mode hits the real Jira
API; mock mode writes the ticket payloads to a local JSON file so you can
see exactly what would have been created.
"""

import json
import sys
from pathlib import Path
from typing import List

sys.path.append(str(Path(__file__).resolve().parent.parent))
from shared.config import config
from log_parser import TestFailure

OUTPUT_DIR = Path(__file__).resolve().parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True)


def create_bug_tickets(failures: List[TestFailure], build_url: str) -> List[str]:
    use_live = config.require_or_warn(config.jira_api_token, "JIRA_API_TOKEN") and \
        config.require_or_warn(config.jira_base_url, "JIRA_BASE_URL")

    created_refs = []
    mock_payloads = []

    for f in failures:
        description = _build_description(f, build_url)
        payload = {
            "fields": {
                "project": {"key": config.jira_project_key},
                "summary": f"[CI Failure] {f.test_name}",
                "description": description,
                "issuetype": {"name": "Bug"},
                "priority": {"name": _severity_to_jira_priority(f.severity)},
                "labels": ["auto-generated", "ci-failure"],
            }
        }

        if use_live:
            import requests
            from requests.auth import HTTPBasicAuth

            url = f"{config.jira_base_url.rstrip('/')}/rest/api/2/issue"
            resp = requests.post(
                url, json=payload,
                auth=HTTPBasicAuth(config.jira_email, config.jira_api_token),
                timeout=15,
            )
            resp.raise_for_status()
            key = resp.json()["key"]
            created_refs.append(key)
            print(f"[jira_bug_creator] Created ticket {key}: {f.test_name}")
        else:
            mock_payloads.append(payload)

    if not use_live:
        out_path = OUTPUT_DIR / "jira_bug_tickets_mock.json"
        out_path.write_text(json.dumps(mock_payloads, indent=2))
        print(f"[jira_bug_creator] MOCK MODE: wrote {len(mock_payloads)} ticket payload(s) to {out_path}")
        created_refs = [f"MOCK-{i+1}" for i in range(len(mock_payloads))]

    return created_refs


def _build_description(f: TestFailure, build_url: str) -> str:
    return (
        f"*Automatically generated by Bug Report & Log Analyzer Agent*\n\n"
        f"h3. Failed Test\n{f.test_name}\n\n"
        f"h3. Error\n{{code}}{f.error_type}: {f.error_message}{{code}}\n\n"
        f"h3. Location\n{f.file_location or 'Not identified'}\n\n"
        f"h3. Root Cause (auto-classified)\n*{f.root_cause_label}*\n{f.root_cause_explanation}\n\n"
        f"h3. Steps to Reproduce\n"
        f"1. Trigger CI pipeline / run: {build_url}\n"
        f"2. Observe test suite containing '{f.test_name}'\n"
        f"3. Confirm failure matches the error above\n\n"
        f"h3. Severity\n{f.severity}\n\n"
        f"h3. CI Build\n{build_url}"
    )


def _severity_to_jira_priority(severity: str) -> str:
    return {"Critical": "Highest", "High": "High", "Medium": "Medium", "Low": "Low"}.get(severity, "Medium")
